version: "3"
services:
  dashboard:
    image: taemon1337/ingress-dashboard:0.0.7
    ports:
      - 8080:80
    depends_on:
      - images.svc.cluster.local
    networks:
      - dashnet
  images.svc.cluster.local:
    image: taemon1337/image-api:0.0.1
    networks:
      - dashnet
networks:
  dashnet: